version: '3'

# Setup Script - Development Tasks
# Consolidated CLI interface for all development operations
# See: /prompts/CLAUDE/CLAUDE-tooling.md for detailed documentation

vars:

tasks:
  python:test:
    desc: Run all Python setup script tests (unit + integration)
    cmds:
      - task: python:test:unit

  python:test:unit:
    desc: Run Python setup script unit tests
    cmds:
      - 'failed=0; for test in python/tests/test_*.nu; do echo "Running: $test"; nu "$test" || { echo "❌ Test failed: $test"; failed=1; }; echo ""; done; if [ $failed -eq 1 ]; then echo "❌ Some tests failed"; exit 1; else echo "✅ All setup script tests passed"; fi'

  python:build:
    desc: "Build standalone Python setup script"
    cmds:
      - mkdir -p dist
      - nu build.nu python
    sources:
      - python/**/*.nu
    generates:
      - dist/setup-python.nu

  go:test:
    desc: Run all Go setup script tests (unit + integration)
    cmds:
      - task: go:test:unit

  go:test:unit:
    desc: Run Go setup script unit tests
    cmds:
      - 'failed=0; for test in go/tests/test_*.nu; do echo "Running: $test"; nu "$test" || { echo "❌ Test failed: $test"; failed=1; }; echo ""; done; if [ $failed -eq 1 ]; then echo "❌ Some tests failed"; exit 1; else echo "✅ All setup script tests passed"; fi'

  go:build:
    desc: "Build standalone Go setup script"
    cmds:
      - mkdir -p dist
      - nu build.nu go
    sources:
      - go/**/*.nu
    generates:
      - dist/setup-go.nu

  java:test:
    desc: Run all Java setup script tests (unit + integration)
    cmds:
      - task: java:test:unit

  java:test:unit:
    desc: Run Java setup script unit tests
    cmds:
      - 'failed=0; for test in java/tests/test_*.nu; do echo "Running: $test"; nu "$test" || { echo "❌ Test failed: $test"; failed=1; }; echo ""; done; if [ $failed -eq 1 ]; then echo "❌ Some tests failed"; exit 1; else echo "✅ All setup script tests passed"; fi'

  java:build:
    desc: "Build standalone Java setup script"
    cmds:
      - mkdir -p dist
      - nu build.nu java
    sources:
      - java/**/*.nu
    generates:
      - dist/setup-java.nu

  build:
    desc: "Build all standalone setup scripts"
    cmds:
      - task: python:build
      - task: go:build
      - task: java:build

  common:test:
    desc: Run common library tests
    cmds:
      - 'failed=0; for test in common/tests/test_*.nu; do echo "Running: $test"; nu "$test" || { echo "❌ Test failed: $test"; failed=1; }; echo ""; done; if [ $failed -eq 1 ]; then echo "❌ Some tests failed"; exit 1; else echo "✅ All setup script tests passed"; fi'

  test:
    desc: Run all tests (Common + Python + Go + Java)
    cmds:
      - task: common:test
      - task: python:test
      - task: go:test
      - task: java:test

  help:
    desc: Show available tasks
    cmds:
      - task --list
